### ISSUE TITLE
A question about the dataset

### ISSUE THREAD

**Issue by seakafuka** [molnarszilard/GIPC_rele#1]
Hello author, your project is very valuable, but I don't see any specific format about the dataset, I only know it contains geometry image, can you give me a reference dataset?

**Comment by molnarszilard** [comment]
Hi! 

Unfortunately, currently I do not have the means to keep my dataset available.

However, You can download ModelNet10 dataset, then in the readme I linked a Matlab script which converts .obj files into .jpg or .png images. After you have the geometry images, you can organize them into a train and test folder.

**Comment by seakafuka** [comment]
Thank you very much for your quick reply, I have in fact obtained some gim.png via matlab, what I would like to know is how do I need to organize my dataset, do I need point cloud data and if so how should I put it together with the images?
Looking forward to your reply

**Comment by molnarszilard** [comment]
For training, you only need the .png images. Inside a root directory, you should have a train and a test folder containing those images. 

Point clouds are mostly useful for data visualization since a gim is not understandable for humans. For example, when you use the trained model to generate new forms, you can convert the input and the output of the model into point clouds and compare them.

**Comment by seakafuka** [comment]
I love you., you're the best programmer.
